from typing import List, Optional
from pydantic import BaseModel

class User(BaseModel):
    owner: str
    name: str
    createdTime: str
    updatedTime: str
    deletedTime: Optional[str]
    id: str
    externalId: Optional[str]
    type: str
    password: Optional[str]
    passwordSalt: Optional[str]
    passwordType: str
    displayName: str
    firstName: Optional[str]
    lastName: Optional[str]
    avatar: str
    avatarType: Optional[str]
    permanentAvatar: Optional[str]
    email: str
    emailVerified: bool
    phone: str
    countryCode: Optional[str]
    region: Optional[str]
    location: Optional[str]
    address: Optional[List[str]]
    affiliation: str
    title: Optional[str]
    idCardType: Optional[str]
    idCard: Optional[str]
    homepage: Optional[str]
    bio: Optional[str]
    tag: str
    language: str
    gender: Optional[str]
    birthday: Optional[str]
    education: Optional[str]
    score: int
    karma: int
    ranking: int
    isDefaultAvatar: bool
    isOnline: bool
    isAdmin: bool
    isForbidden: bool
    isDeleted: bool
    signupApplication: str
    hash: Optional[str]
    preHash: Optional[str]
    accessKey: Optional[str]
    accessSecret: Optional[str]
    createdIp: Optional[str]
    lastSigninTime: Optional[str]
    lastSigninIp: Optional[str]
    github: Optional[str]
    google: Optional[str]
    qq: Optional[str]
    wechat: Optional[str]
    facebook: Optional[str]
    dingtalk: Optional[str]
    weibo: Optional[str]
    gitee: Optional[str]
    linkedin: Optional[str]
    wecom: Optional[str]
    lark: Optional[str]
    gitlab: Optional[str]
    adfs: Optional[str]
    baidu: Optional[str]
    alipay: Optional[str]
    casdoor: Optional[str]
    infoflow: Optional[str]
    apple: Optional[str]
    azuread: Optional[str]
    azureadb2c: Optional[str]
    slack: Optional[str]
    steam: Optional[str]
    bilibili: Optional[str]
    okta: Optional[str]
    douyin: Optional[str]
    line: Optional[str]
    amazon: Optional[str]
    auth0: Optional[str]
    battlenet: Optional[str]
    bitbucket: Optional[str]
    box: Optional[str]
    cloudfoundry: Optional[str]
    dailymotion: Optional[str]
    deezer: Optional[str]
    digitalocean: Optional[str]
    discord: Optional[str]
    dropbox: Optional[str]
    eveonline: Optional[str]
    fitbit: Optional[str]
    gitea: Optional[str]
    heroku: Optional[str]
    influxcloud: Optional[str]
    instagram: Optional[str]
    intercom: Optional[str]
    kakao: Optional[str]
    lastfm: Optional[str]
    mailru: Optional[str]
    meetup: Optional[str]
    microsoftonline: Optional[str]
    naver: Optional[str]
    nextcloud: Optional[str]
    onedrive: Optional[str]
    oura: Optional[str]
    patreon: Optional[str]
    paypal: Optional[str]
    salesforce: Optional[str]
    shopify: Optional[str]
    soundcloud: Optional[str]
    spotify: Optional[str]
    strava: Optional[str]
    stripe: Optional[str]
    tiktok: Optional[str]
    tumblr: Optional[str]
    twitch: Optional[str]
    twitter: Optional[str]
    typetalk: Optional[str]
    uber: Optional[str]
    vk: Optional[str]
    wepay: Optional[str]
    xero: Optional[str]
    yahoo: Optional[str]
    yammer: Optional[str]
    yandex: Optional[str]
    zoom: Optional[str]
    metamask: Optional[str]
    web3onboard: Optional[str]
    custom: Optional[str]
    preferredMfaType: Optional[str]